// Generated by `bun init`

// Browser vendor-prefix augmentations
interface Window {
  /** Safari / older Chrome fallback for the Web Audio API context. */
  webkitAudioContext?: typeof AudioContext;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.css" {}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
